version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:15
    container_name: postgres_gestao_acesso
    restart: always
    environment:
      POSTGRES_USER: valdeli
      POSTGRES_PASSWORD: aS1057
      POSTGRES_DB: gestao_acesso
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
